/** Shared bookable service labels — used by seed data and booking fallbacks. */
export const BARBER_SERVICE_LABELS = [
  "Haircut (Adults) — K130",
  "Children Haircut (Under 13) — K80",
  "Caucasian Haircut — K250",
  "Children Haircut + Black Dye — K150",
  "Shave — K60",
  "Beard Trim & Shape — K70",
  "Cut & Beard Trim — K180",
  "Lining Only — K40",
  "Lining and Dye — K70",
  "Haircut + Black Dye — K180",
  "Haircut + Blonde Dye — K300",
  "Haircut + Magic Powder — K230",
  "Magic Powder — K150",
  "Hair Coloring / Dye — K150",
  "S Curl — K200",
  "Facial Scrub — K150",
  "Neck Massage — K150",
] as const;

export const SALON_SERVICE_LABELS = [
  "Goddess Braids (Medium) — K380",
  "Goddess Braids (Small) — K450",
  "Goddess Braids (Big) — K300",
  "Knotless Braids (Medium) — K350",
  "Knotless Braids (Small) — K400",
  "Box Braids (Medium) — K300",
  "Cornrows — K300",
  "Butterfly Braids (Medium) — K400",
  "Passion Twist (Medium) — K350",
  "Fox Locks — K400",
  "Crochet Braids — K350",
  "Pick and Drop Braids — K400",
  "Plain Mukule — K150",
  "Cornrows with Wig — K200",
  "Twin Braids — K200",
  "Natural Twist — K250",
  "Mukule with Wig — K250",
  "Wig Installation — K350",
  "Wig Making — K350",
  "Wig Wash & Steampod — K250",
  "Open Weave — K300",
  "Closed Weave — K300",
  "Weave with Closure — K350",
  "Wash and Set — K150",
  "Wash and Blow — K100",
  "Hair Wash — K100",
  "Hair Treatment — K250",
  "Silk Press — K300",
  "Hair Coloring / Dye — K150",
  "Makeup with Lash Extension — K350",
  "Makeup without Lash Extension — K300",
  "Classic Lashes — K300",
  "Hybrid Lashes — K350",
  "Mega Volume Lashes — K400",
  "Eyebrows Threading — K100",
  "Facial Treatment — K150",
  "Acrylic Nails — K400",
  "Manicure — K100",
  "Pedicure Only — K400",
  "Pedicure & Manicure — K450",
  "Stick-on Nails — K300",
  "Rubber Gel Nails — K380",
  "Toe Nails — K250",
  "Nail Refill — K300",
] as const;
